# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanmusuequipment',
            name='equipment_pic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
